#!/usr/bin/env python
import argparse
import ocdsdata.cli.util


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument("--verbose", help="increase output verbosity",
                        action="store_true")

    subparsers = parser.add_subparsers(dest='subcommand')

    commands = ocdsdata.cli.util.gather_cli_commands_instances()

    for command in commands.values():
        command.configure_subparser(subparsers.add_parser(command.command))

    args = parser.parse_args()

    if args.subcommand and args.subcommand in commands.keys():
        commands[args.subcommand].run_command(args)
    else:
        print("Please select a subcommand (try --help)")


if __name__ == '__main__':
    main()
